<a href="https://colab.research.google.com/github/Retails0531/Bigdata1st/blob/main/UNLV%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data1 = pd.read_csv('./drive/MyDrive/UNLV_project/data_RNA_Seq_v2_mRNA_median_all_sample_Zscores.txt', sep='\t')
data2 = pd.read_csv('./drive/MyDrive/UNLV_project/data_bcr_clinical_data_patient.txt', sep='\t')

Mounted at /content/drive

In [2]:
data1 = data1.set_index('Hugo_Symbol', drop = True)

In [3]:
data1 = data1.T
data1.rename(index = lambda x : str(x).replace('-01', ''), inplace = True)
data1 = data1.iloc[1:]
data1

Hugo_Symbol,LOC100130426,UBE2Q2P3,UBE2Q2P3,HMGB1P1,TIMM23,MOXD2,LOC155060,RNU12-2P,SSX9,LOC317712,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,FLJ10821,ZZZ3,TPTEP1,AKR1C6P
TCGA-05-4244,-2.2883,0.0380,0.0691,-1.9057,-0.0395,NaN,1.0624,0.5387,-1.2501,NaN,...,-0.2092,-0.4448,-0.2293,-1.8833,0.9850,-0.4967,-0.2737,-0.4482,-1.0407,-1.2966
TCGA-05-4249,-2.2883,-0.3514,0.1971,-0.2950,0.1945,NaN,-0.0690,1.4599,-1.2501,NaN,...,0.7816,0.8157,0.4243,-0.1788,-0.1119,-0.8791,0.3183,0.0984,1.0324,-1.2966
TCGA-05-4250,-2.2883,-0.3435,-0.7239,-1.9091,0.7761,NaN,-1.4074,-2.1796,-1.2501,NaN,...,0.7041,0.0911,-0.6346,-0.0054,-1.8251,0.8248,0.3805,-0.6777,-1.0698,-1.2966
TCGA-05-4382,-2.2883,0.1873,-0.4402,-0.5333,-0.1787,NaN,0.5870,-0.6958,-0.9868,NaN,...,-0.1734,-0.0352,-0.2710,0.5825,0.3717,1.2704,0.3781,-0.0188,-0.0218,-1.2966
TCGA-05-4384,-2.2883,-1.2251,-1.3555,-0.8895,-1.1778,NaN,0.7614,-0.3706,-1.2501,NaN,...,1.3474,1.1341,0.7826,-0.7635,-0.1493,-0.1648,1.2559,0.2385,1.5166,-1.2966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-NJ-A55O,-2.2883,0.5729,1.0176,-0.0218,0.0408,NaN,0.6719,0.7543,-1.2501,NaN,...,-0.1517,-0.1613,0.2250,-0.2732,-0.3860,0.2930,0.6698,-0.3969,1.7447,-1.2966
TCGA-NJ-A55R,-2.2883,-0.1679,-0.0462,-0.8099,-0.3206,NaN,1.1540,-0.1200,-1.2501,NaN,...,0.3282,0.1494,1.1546,0.4441,-0.2421,-0.3319,1.5561,-0.2637,1.9706,0.5663
TCGA-NJ-A7XG,-2.2883,1.8645,2.7613,-0.4522,-0.6611,NaN,1.0220,-2.1796,-1.2501,NaN,...,-2.0722,-1.7646,0.5444,-0.6192,-1.4443,-1.2127,0.8153,-1.3431,-1.1463,-1.2966
TCGA-O1-A52J,-2.2883,0.4532,1.0870,-1.3473,0.7679,NaN,0.1428,2.9555,-1.2501,NaN,...,2.5448,1.1317,0.7244,-1.9766,-0.1344,0.4326,0.9605,-1.0035,1.0542,-0.3735
TCGA-S2-AA1A,-2.2883,0.9225,-0.2293,-0.7319,-1.1610,NaN,1.1789,-0.2677,-1.2501,NaN,...,0.7138,0.0837,1.8159,-0.8773,-0.9062,0.7905,1.0496,-0.8107,1.4044,-1.2966

In [4]:
data2 = data2.iloc[4:]
data2 = data2[['Patient Identifier', 'Overall Survival Status', 'Overall Survival (Months)']]
data2 = data2.set_index('Patient Identifier', drop = True)
data2

                   Overall Survival Status Overall Survival (Months)
Patient Identifier
TCGA-05-4244                      0:LIVING                         0
TCGA-05-4245                      0:LIVING                     23.98
TCGA-05-4249                      0:LIVING                     50.03
TCGA-05-4250                    1:DECEASED                      3.98
TCGA-05-4382                      0:LIVING                     19.94
...                                    ...                       ...
TCGA-NJ-A55O                      0:LIVING                      0.43
TCGA-NJ-A55R                      0:LIVING                     19.81
TCGA-NJ-A7XG                      0:LIVING                     20.27
TCGA-O1-A52J                    1:DECEASED                     59.07
TCGA-S2-AA1A                      0:LIVING                     16.85

[522 rows x 2 columns]

In [5]:
data = data2.merge(data1, left_on = 'Patient Identifier', right_index = True)

In [6]:
missing_data = data.isnull().sum() / len(data) > 0.8

missing_data = missing_data.to_frame()
missing_data.loc[missing_data[0] == True]

               0
MOXD2       True
LOC317712   True
SPATA31B1P  True
REXO1L6P    True
PPBPL1      True
...          ...
UNCX        True
VTRNA1-1    True
VTRNA1-2    True
VTRNA1-3    True
XKRY        True

[418 rows x 1 columns]

In [7]:
missing_data_index = missing_data.loc[missing_data[0] == True, :].index
data = data.drop(missing_data_index, axis = 1)
data

,Overall Survival Status,Overall Survival (Months),LOC100130426,UBE2Q2P3,UBE2Q2P3,HMGB1P1,TIMM23,LOC155060,RNU12-2P,SSX9,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,FLJ10821,ZZZ3,TPTEP1,AKR1C6P
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-05-4244,0:LIVING,0,-2.2883,0.0380,0.0691,-1.9057,-0.0395,1.0624,0.5387,-1.2501,...,-0.2092,-0.4448,-0.2293,-1.8833,0.9850,-0.4967,-0.2737,-0.4482,-1.0407,-1.2966
TCGA-05-4249,0:LIVING,50.03,-2.2883,-0.3514,0.1971,-0.2950,0.1945,-0.0690,1.4599,-1.2501,...,0.7816,0.8157,0.4243,-0.1788,-0.1119,-0.8791,0.3183,0.0984,1.0324,-1.2966
TCGA-05-4250,1:DECEASED,3.98,-2.2883,-0.3435,-0.7239,-1.9091,0.7761,-1.4074,-2.1796,-1.2501,...,0.7041,0.0911,-0.6346,-0.0054,-1.8251,0.8248,0.3805,-0.6777,-1.0698,-1.2966
TCGA-05-4382,0:LIVING,19.94,-2.2883,0.1873,-0.4402,-0.5333,-0.1787,0.5870,-0.6958,-0.9868,...,-0.1734,-0.0352,-0.2710,0.5825,0.3717,1.2704,0.3781,-0.0188,-0.0218,-1.2966
TCGA-05-4384,0:LIVING,13.99,-2.2883,-1.2251,-1.3555,-0.8895,-1.1778,0.7614,-0.3706,-1.2501,...,1.3474,1.1341,0.7826,-0.7635,-0.1493,-0.1648,1.2559,0.2385,1.5166,-1.2966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-NJ-A55O,0:LIVING,0.43,-2.2883,0.5729,1.0176,-0.0218,0.0408,0.6719,0.7543,-1.2501,...,-0.1517,-0.1613,0.2250,-0.2732,-0.3860,0.2930,0.6698,-0.3969,1.7447,-1.2966
TCGA-NJ-A55R,0:LIVING,19.81,-2.2883,-0.1679,-0.0462,-0.8099,-0.3206,1.1540,-0.1200,-1.2501,...,0.3282,0.1494,1.1546,0.4441,-0.2421,-0.3319,1.5561,-0.2637,1.9706,0.5663
TCGA-NJ-A7XG,0:LIVING,20.27,-2.2883,1.8645,2.7613,-0.4522,-0.6611,1.0220,-2.1796,-1.2501,...,-2.0722,-1.7646,0.5444,-0.6192,-1.4443,-1.2127,0.8153,-1.3431,-1.1463,-1.2966
TCGA-O1-A52J,1:DECEASED,59.07,-2.2883,0.4532,1.0870,-1.3473,0.7679,0.1428,2.9555,-1.2501,...,2.5448,1.1317,0.7244,-1.9766,-0.1344,0.4326,0.9605,-1.0035,1.0542,-0.3735
TCGA-S2-AA1A,0:LIVING,16.85,-2.2883,0.9225,-0.2293,-0.7319,-1.1610,1.1789,-0.2677,-1.2501,...,0.7138,0.0837,1.8159,-0.8773,-0.9062,0.7905,1.0496,-0.8107,1.4044,-1.2966

In [16]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(data, test_size = 0.2, random_state=83, shuffle =True)
train_set, val_set = train_test_split(train_set, test_size = 0.2, random_state = 83, shuffle = True)
train_label = train_set[['Overall Survival Status','Overall Survival (Months)']]
train_set.drop(['Overall Survival Status','Overall Survival (Months)'],axis=1)
test_label = test_set[['Overall Survival Status','Overall Survival (Months)']]
test_set.drop(['Overall Survival Status','Overall Survival (Months)'],axis=1)
val_label = val_set[['Overall Survival Status','Overall Survival (Months)']]
val_set.drop(['Overall Survival Status','Overall Survival (Months)'],axis=1)

,LOC100130426,UBE2Q2P3,UBE2Q2P3,HMGB1P1,TIMM23,LOC155060,RNU12-2P,SSX9,EZHIP,EFCAB8,...,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,FLJ10821,ZZZ3,TPTEP1,AKR1C6P
Patient Identifier,,,,,,,,,,,,,,,,,,,,,
TCGA-99-8025,-2.2883,-0.1062,-0.9168,-0.7216,0.4419,0.8203,-1.0885,-1.2501,-0.9569,-1.6633,...,-1.0907,-0.3162,-0.1788,1.2070,-0.4885,0.5022,-0.6095,-0.8676,-0.0956,-1.2966
TCGA-NJ-A4YF,-2.2883,0.0533,0.3675,-0.6634,3.1340,1.1313,-2.1796,-1.2501,-0.9569,4.5322,...,0.1204,0.0610,1.1970,0.9306,-1.8041,-0.5333,0.3025,-0.7789,-1.3658,-1.2966
TCGA-97-7547,-2.2883,0.7457,0.6588,-0.2446,-1.4747,-0.6334,-2.1796,-1.2501,-0.9569,-1.6633,...,1.3124,0.5236,1.2728,-1.5581,0.8952,-1.2860,1.5157,-0.4880,-0.3604,-1.2966
TCGA-55-7903,-2.2883,-0.4910,0.1013,-0.4440,-0.7755,0.3144,0.4436,-1.2501,-0.5551,-0.5105,...,-0.0712,-0.4949,0.8468,0.9819,0.4587,-0.7070,-1.3370,0.1148,-1.5528,-1.2966
TCGA-55-7815,-2.2883,-1.6751,-1.9263,0.0474,0.2473,-3.3476,-2.1796,-1.2501,-0.9569,-1.6633,...,1.3512,2.9214,-1.8527,-2.2402,1.0473,-3.3891,0.2733,0.8226,-1.9169,-1.2966
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-67-3773,-2.2883,-2.1934,-0.1872,1.4333,0.4744,-0.5319,-2.1796,-1.2501,-0.9569,0.6824,...,-0.9232,-1.1994,-1.9193,-1.4873,0.6246,0.1382,-2.0273,-0.0091,1.2432,-1.2966
TCGA-55-6985,-2.2883,-0.3022,0.4983,-0.4278,-0.0288,-0.2997,-2.1796,-1.2501,-0.4028,-0.7338,...,-0.6334,-0.7801,-0.0138,0.5521,-0.0270,0.3800,0.1048,-0.1235,0.5897,-1.2966
TCGA-97-7554,-2.2883,-0.8841,-1.9136,-0.8696,-0.6384,-0.9709,-2.1796,-1.2501,-0.9569,-0.5072,...,0.3857,1.0000,-0.8378,1.0335,0.4559,0.3111,-0.2493,-0.4195,-0.5979,-1.2966
TCGA-55-6642,-2.2883,0.4420,-1.2814,-0.1146,0.2963,-0.6030,0.9979,-1.2501,-0.9569,-0.8230,...,1.1134,1.0236,-0.0894,-0.9384,1.0690,-0.1921,2.3230,1.1588,1.2388,-1.2966
TCGA-50-5946,-2.2883,0.8037,0.6377,1.2792,-0.4422,0.7996,-1.1217,-0.6404,-0.9569,3.9125,...,-0.3138,-0.3703,1.6059,1.2045,0.6079,-1.1883,0.1904,1.1053,-1.1825,-1.2966

In [17]:
train_label

                   Overall Survival Status Overall Survival (Months)
Patient Identifier
TCGA-78-7542                    1:DECEASED                     10.55
TCGA-55-8615                      0:LIVING                     14.65
TCGA-93-A4JP                      0:LIVING                     18.99
TCGA-78-7539                      0:LIVING                     25.99
TCGA-55-8620                    1:DECEASED                     12.32
...                                    ...                       ...
TCGA-69-7980                      0:LIVING                      13.5
TCGA-73-A9RS                    1:DECEASED                     11.17
TCGA-55-A48Z                      0:LIVING                     21.39
TCGA-50-5051                    1:DECEASED                      15.7
TCGA-55-6978                    1:DECEASED                      5.78

[329 rows x 2 columns]